### PR TITLE
Implement runtime sleep type changes

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Untested

**Comment by mkopec** [comment]
Do we need to have this? If I understand correctly, enabling S0ix in EC does not prevent from also using S3.

**Review by mkopec — CHANGES_REQUESTED** [review]
This change breaks opportunistic (runtime) S0ix which is still enabled when S3 is selected in the setup menu. I can see that the SLP_S0# residency counter increases while the screen is off, but the EC now doesn't stop polling PECI and the fans spin up to 100%. Overall this change is not needed.

**Comment by miczyg1** [comment]
> This change breaks opportunistic (runtime) S0ix which is still enabled when S3 is selected in the setup menu.
> 
> Opportunistic S0ix is entered while idle and the screen is off (or in panel self-refresh). I can see that the SLP_S0# residency counter increases while the screen is off, but the EC now doesn't stop polling PECI and the fans spin up to 100%. Overall this change is not needed.

OK so I have to change ACPI more to avoid opportunistic S0IX. Probably would be enough to set PEP device status to 0 if S0iX disabled.

**Comment by miczyg1** [comment]
> Do we need to have this? If I understand correctly, enabling S0ix in EC does not prevent from also using S3. This change just prevents the S0ix codepath from running when S3 is used, but it won't do so anyway if SLP_S0# never asserts.

That's a good question. I saw some comments that certain operations are time/latency sensitive so wanted to avoid unwanted code execution as much as possible. Given your reasons, we should not even have USE_S0IX preprocessor IFs in such case, because we could do both anyways.

**Comment by miczyg1** [comment]
Superseded by https://github.com/Dasharo/ec/pull/31

**Pull request closed without merging**
