### PR TITLE
USB-PD stability fixes

### PR DESCRIPTION
**Pull request by mkopec**
Removing VIN_3V3 from the PD controller causes it to reset and boot in dead battery mode if a PD power supply is attached. So, keep the S5 power plane on after shutdown, so that the PD controller keeps running.

Clear the Dead Battery Flag as soon as we exit G3, to allow the PD controller to switch power supply from Vbus to VIN_3V3 and operate normally.

Throttle for 3 seconds on AC detach to avoid crashes due to a surge in battery load.

Also enable HPB on OZ26786 to prevent triggering overcurrent conditions.

### CODE REVIEW

**Review by miczyg1 — APPROVED** [review]

**Comment by mkopec** [comment]
@miczyg1 I'm just waiting for initial test reports from @wessel-novacustom to confirm that this actually solves problems on his side as well

**Comment by mkopec** [comment]
Trying to enable the PROCHOT signal on GPIO9 of the PD controller to automatically throttle on plug insertion / other power changes. Controller seems to reject any changes I make to the GPIO configuration register. TPS65993 datasheet would really help here...

**Comment by mkopec** [comment]
Restricted current limits to 85% of supply current on oz26786 models, to avoid triggering PSU OCP. Added a debug option for enabling battery boost (which controls the Psys power limits, HPB is always enabled as a safety precaution)

**Comment by mkopec** [comment]
Enabled H_PROCHOT_EC for all NovaCustom models, needed to throttle for 3 seconds after AC detach as per service manual.

**Comment by mkopec** [comment]
Reverted the power state change since it seemed to introduce regressions on NS5xPU. I guess we'd need to handle waking up the PD controller properly, because it can NAK i2c transactions in sleep states, and we were not doing any retries

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
