### PR TITLE
Reset ps/2 ports on init

### PR DESCRIPTION
**Pull request by mkopec**
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by mkopec** [comment]
This seems to cause other problems with Windows, converting to draft for now

**Comment by miczyg1** [comment]
Shouldn't Windows use I2C instead?

**Comment by miczyg1** [comment]
> This seems to cause other problems with Windows, converting to draft for now

What if we leave the coreboot's ps2_init? Is also Windows having problems?

**Comment by mkopec** [comment]
Done in #5, closing

**Pull request closed without merging**
