### PR TITLE
Battery Thresholds

### PR DESCRIPTION
**Pull request by mkopec**
Fix the threshold logic to prevent unnecessary charging. Set the default thresholds for all models to 95-98%.

### CODE REVIEW

**Review by miczyg1 — APPROVED** [review]

**Comment by miczyg1** [comment]
@mkopec the path to spdx lint check is wrong?

**Comment by mkopec** [comment]
@miczyg1 Right, fixed in https://github.com/Dasharo/ec/pull/38

**Comment by miczyg1** [comment]
> @miczyg1 ~Right, fixed in #38~ nope, still broken. let me figure out what's going on here

Maybe this branch needs rebase? I just merged the fix_ci

**Comment by mkopec** [comment]
@miczyg1 rebased, CI passes now.

**Pull request merged**
